### ISSUE TITLE
There is no source code

### ISSUE THREAD

**Issue by MingyuKim87** [jinxu06/metafun-tensorflow#1]
Hello, I'm Mingyu Kim who sent a mail for Meta-Fun code.

This work is very impressive for me to re-implement your code for my research. 

I have been looking forward to your new feed, but there is no source code except descriptions. 

So that, I would like to upload a main body of your code.

**Comment by jinxu06** [comment]
Hello Mingyu, thanks for your interest in our work, and sorry for the long wait! 
I have now released an initial version of our code (It is possible that we might need to update it later). 
Hope the code is helpful for your research and any feedback is welcome.
